# Generated by Django 4.0.6 on 2022-09-03 01:45

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200, null=True, unique=True)),
                ('Adresse', models.CharField(max_length=200, null=True)),
                ('cp', models.CharField(max_length=200, null=True)),
                ('ville', models.CharField(max_length=200, null=True)),
                ('remise', models.CharField(max_length=200, null=True)),
                ('divers', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200, null=True, unique=True)),
                ('Adresse', models.CharField(max_length=200, null=True)),
                ('cp', models.CharField(max_length=200, null=True)),
                ('ville', models.CharField(max_length=200, null=True)),
                ('remise', models.CharField(max_length=200, null=True)),
                ('divers', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('temps_en_secondes', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GestioncM',
            fields=[
                ('mission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.mission')),
                ('enonce', models.TextField()),
                ('nbre_ref', models.IntegerField(default=0, null=True)),
                ('min_qte', models.IntegerField(default=0, null=True)),
                ('max_qte', models.IntegerField(default=0, null=True)),
            ],
            bases=('base.mission',),
        ),
        migrations.CreateModel(
            name='QuizzM',
            fields=[
                ('mission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.mission')),
                ('question', models.CharField(max_length=200, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('rep', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=6)),
                ('points', models.IntegerField(null=True)),
            ],
            bases=('base.mission',),
        ),
        migrations.CreateModel(
            name='sanctionsM',
            fields=[
                ('mission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.mission')),
                ('intitule', models.CharField(max_length=200, null=True)),
                ('pointsA', models.IntegerField(default=0, null=True)),
                ('pointsR', models.IntegerField(default=0, null=True)),
            ],
            bases=('base.mission',),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200, null=True, unique=True)),
                ('prix_achatHT', models.CharField(max_length=200, null=True)),
                ('prix_venteHT', models.CharField(max_length=200, null=True)),
                ('prix_venteTTC', models.CharField(max_length=200, null=True)),
                ('TVA', models.CharField(max_length=200, null=True)),
                ('stock', models.CharField(max_length=200, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Mission_Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_restant', models.IntegerField(null=True)),
                ('enonce', models.TextField(default='')),
                ('reponse', models.CharField(default='', max_length=80)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, null=True, unique=True)),
                ('password1', models.CharField(max_length=80, null=True)),
                ('password2', models.CharField(max_length=80, null=True)),
                ('points', models.IntegerField(null=True)),
                ('mission_courante', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.mission_joueur')),
                ('missions_passe', models.ManyToManyField(default='', related_name='missions_passe', to='base.mission_joueur')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
