# Generated by Django 4.0.6 on 2022-09-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission_joueur',
            name='enonce',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='mission_joueur',
            name='reponse',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
