# Generated by Django 4.0.6 on 2022-09-18 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='type_de_missions',
            field=models.ManyToManyField(related_name='type_de_missions', to='base.choix'),
        ),
        migrations.AlterField(
            model_name='mission_joueur',
            name='debut',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 20, 14, 5, 487277)),
        ),
    ]
