# Generated by Django 4.0.6 on 2022-09-18 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_joueur_type_de_missions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission_joueur',
            name='debut',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 20, 28, 28, 292637)),
        ),
    ]
