# Generated by Django 4.0.6 on 2022-09-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_mission_joueur_enonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestioncm',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
