# Generated by Django 4.0.6 on 2022-12-29 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_mission_joueur_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission_joueur',
            name='debut',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 19, 47, 37, 479801, tzinfo=utc)),
        ),
    ]
