# Generated by Django 4.0.6 on 2022-09-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_gestioncm_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='points_depart',
            field=models.IntegerField(null=True),
        ),
    ]
