# Generated by Django 4.0.6 on 2022-09-18 21:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_mission_joueur_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission_joueur',
            name='debut',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 23, 41, 0, 694452)),
        ),
        migrations.AlterField(
            model_name='quizzm',
            name='type_de_quizz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.choix'),
        ),
    ]
