# Generated by Django 4.0.6 on 2022-09-12 23:54

import base.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_joueur_points_depart'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='joueur',
            managers=[
                ('objects', base.managers.CustomUserManager()),
            ],
        ),
    ]
