# Generated by Django 4.0.6 on 2022-09-13 00:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_joueur_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='joueur',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
