# Generated by Django 4.0.6 on 2022-09-18 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_mission_joueur_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission_joueur',
            name='debut',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 23, 50, 34, 971836)),
        ),
    ]
